### PR TITLE
UPDATE: scraped and added 2019, 2020 data

### PR DESCRIPTION
**Pull request by gauravk268**

### CODE REVIEW

**Comment by gauravk268** [comment]
UPDATE:
scraped and added 2019, 2020 data
added python notebook to find possible colleges from JEE Main/Adv Rank in India

**Comment by seshaljain** [comment]
Hey! Thank you for the contributions. I haven't been able to give this project much time due to other commitments.

I think it would be better if we keep the possible colleges in memory, rather than writing it onto the disk. 
Would you like to work on the filtering to make it more fine-grained? Feel free to make an issue for the same. Some work needs to be done in the Notebook, I can merge the data you have scraped though.

**Comment by gauravk268** [comment]
I will be making a front end for college shortlist using the data in csv.

Jupyter notebook i made only for my personal use, and after that added comments for others to use.
I have changed the college showing in notebook itself as well as in spreadsheet and will add the filtering part in front end.

**Comment by gauravk268** [comment]
You can merge it now, i have moved the notebook to another branch. Will add it later after improving.

**Pull request merged**
